<?php
/**
 * @file
 * mock_cluster module.
 */

/**
 * Implements hook_config_info().
 */
function mock_cluster_config_info() {
  $prefixes['mock_cluster.settings'] = array(
    'label' => t('Github Node settings'),
    'group' => t('Configuration'),
  );
  return $prefixes;
}

/**
 * Implements hook_permission().
 */
function mock_cluster_permission() {
  return array(
    'administer mock cluster' => array(
      'title' => t('Administer mock cluster'),
      'description' => t('Control mock_cluster settings'),
      'restrict access' => TRUE,
    ),
    'administer mock agents' => array(
      'title' => t('Administer mock agents'),
      'description' => t('Control agents'),
      'restrict access' => TRUE,
    ),
  );
}

/**
 * Implements hook_load().
 */
function mock_agent_load($MAC){
  return db_select('mock_agents', 'ma')
    ->fields('ma')
    ->condition('MAC', $MAC)
    ->execute()
    ->fetchAssoc();
}

/**
 * Menu item title callback - use the user name.
 */
function mock_agent_title($agent) {
  return is_object($agent) ? $agent->MAC : '';
}

/**
 * Implements hook_menu().
 */
function mock_cluster_menu() {
  $items = array();

  $items['mock_cluster/register'] = array(
    'type' => MENU_CALLBACK,
    'title' => 'Mock Agent register callback',
    'page callback' => 'mock_cluster_register',
    'file' => 'mock_cluster.agent.inc',
    'access callback' => TRUE,
  );

  $items['admin/config/mock_cluster'] = array(
    'title' => 'Mock cluster configuration',
    'description' => 'Configure mock cluster.',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('mock_cluster_configure'),
    'access arguments' => array('administer mock cluster'),
    'file' => 'mock_cluster.admin.inc',
  );
  
  $items['agents'] = array(
    'title' => 'Agents',
    'page callback' => 'mock_cluster_agents',
    'access arguments' => array('access content'),
    'file' => 'mock_cluster.pages.inc',
    'weight' => -10, 
    'menu_name' => 'menu-github-pages',
  );

  $items['agents/%mock_cluster'] = array(
    'type' => MENU_CALLBACK,    
    'title callback' => 'mock_agent_title',
    'title arguments' => array(1),
    'page callback' => 'mock_cluster_agent',
    'page arguments' => array(1),
    'access arguments' => array('access content'),
    'file' => 'mock_cluster.pages.inc',
  );
  
  $items['agents/%mock_cluster/delete'] = array(
    'title callback' => 'mock_agent_title',
    'title arguments' => array(1),
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('mock_agent_delete', 1),
    'access callback' => 'user_access',
    'access arguments' => array('administer mock agents'),
    'file' => 'mock_cluster.pages.inc',
    'type' => MENU_CALLBACK,
  );

  $items['agents/%mock_cluster/activate'] = array(
    'title callback' => 'mock_agent_title',
    'title arguments' => array(1),
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('mock_agent_activate', 1),
    'access callback' => 'user_access',
    'access arguments' => array('administer mock agents'),
    'file' => 'mock_cluster.pages.inc',
    'type' => MENU_CALLBACK,
  );

  $items['agents/%mock_cluster/block'] = array(
    'title callback' => 'mock_agent_title',
    'title arguments' => array(1),
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('mock_agent_block', 1),
    'access callback' => 'user_access',
    'access arguments' => array('administer mock agents'),
    'file' => 'mock_cluster.pages.inc',
    'type' => MENU_CALLBACK,
  );
  return $items;
}
